const colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple'];
    const videos = ['videos/roll1.mp4', 'videos/roll2.mp4', 'videos/roll3.mp4'];
        const bannersTop = ['images/banner1.jpg', 'images/banner2.jpg', 'images/banner3.jpg'];
            const bannersBottom = ['images/banner4.jpg', 'images/banner5.jpg', 'images/banner6.jpg'];
                let videoIndex = 0;
                    let rollCount = 0;

                        function createDice(count) {
                                const container = document.getElementById('diceContainer');
                                        container.innerHTML = '';
                                                for (let i = 0; i < count; i++) {
                                                            const dice = document.createElement('div');
                                                                        dice.classList.add('dice');
                                                                                    const dot = document.createElement('div');
                                                                                                dot.classList.add('dot');
                                                                                                            dice.appendChild(dot);
                                                                                                                        container.appendChild(dice);
                                                                                                                                }
                                                                                                                                    }

                                                                                                                                        function startRoll(mode) {
                                                                                                                                                // ⬇️ Direct jump to top
                                                                                                                                                        window.scrollTo(0, 0);

                                                                                                                                                                const overlay = document.getElementById('videoOverlay');
                                                                                                                                                                        const video = document.getElementById('rollVideo');
                                                                                                                                                                                const sound = document.getElementById('rollSound');
                                                                                                                                                                                        const bannerTop = document.getElementById('bannerTop');
                                                                                                                                                                                                const bannerBottom = document.getElementById('bannerBottom');

                                                                                                                                                                                                        document.body.style.overflow = 'hidden';
                                                                                                                                                                                                                overlay.style.display = 'flex';

                                                                                                                                                                                                                        // 🎥 set video
                                                                                                                                                                                                                                video.src = videos[videoIndex];
                                                                                                                                                                                                                                        video.play();

                                                                                                                                                                                                                                                // 🔊 set sound (ikaw magpapalit ng file dito)
                                                                                                                                                                                                                                                        sound.src = "sounds/roll.mp3"; 
                                                                                                                                                                                                                                                                sound.play();

                                                                                                                                                                                                                                                                        rollCount++;

                                                                                                                                                                                                                                                                                if (rollCount % 2 === 1) {
                                                                                                                                                                                                                                                                                            const indexTop = ((rollCount - 1) / 2) % bannersTop.length;
                                                                                                                                                                                                                                                                                                        bannerTop.src = bannersTop[indexTop];
                                                                                                                                                                                                                                                                                                                    bannerTop.style.display = "block";
                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                        bannerTop.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                        if (rollCount % 2 === 1) {
                                                                                                                                                                                                                                                                                                                                                                    const indexBottom = ((rollCount - 1) / 2) % bannersBottom.length;
                                                                                                                                                                                                                                                                                                                                                                                bannerBottom.src = bannersBottom[indexBottom];
                                                                                                                                                                                                                                                                                                                                                                                            bannerBottom.style.visibility = "visible";
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                bannerBottom.style.visibility = "hidden";
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                videoIndex = (videoIndex + 1) % videos.length;

                                                                                                                                                                                                                                                                                                                                                                                                                                        video.onended = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    overlay.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.body.style.overflow = 'auto';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (mode === 'normal') rollAgain();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else rollSpecific(mode);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function rollAgain() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                createDice(4);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const availableColors = [...colors];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                shuffleArray(availableColors);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const diceElements = document.querySelectorAll('.dice');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (let i = 0; i < diceElements.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            diceElements[i].style.backgroundColor = availableColors[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function rollSpecific(excludeColor) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    createDice(4);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const diceElements = document.querySelectorAll('.dice');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const possibleColors = colors.filter(c => c !== excludeColor);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const chance = Math.random() * 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let sameCount = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (chance < 40) sameCount = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (chance < 70) sameCount = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else if (chance < 90) sameCount = 3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else sameCount = 4;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (sameCount === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        shuffleArray(possibleColors);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (let i = 0; i < diceElements.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    diceElements[i].style.backgroundColor = possibleColors[i % possibleColors.length];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const sameColor = possibleColors[Math.floor(Math.random() * possibleColors.length)];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let otherColors = possibleColors.filter(c => c !== sameColor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shuffleArray(otherColors);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let diceColors = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (let i = 0; i < sameCount; i++) diceColors.push(sameColor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (let i = sameCount; i < 4; i++) diceColors.push(otherColors.pop());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shuffleArray(diceColors);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        diceElements.forEach((dice, idx) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dice.style.backgroundColor = diceColors[idx];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function shuffleArray(arr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let i = arr.length - 1; i > 0; i--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const j = Math.floor(Math.random() * (i + 1));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [arr[i], arr[j]] = [arr[j], arr[i]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return arr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }